backend:
  name: git-gateway
  branch: main
  identity_url: https://dev-c2cpurjjmav12oqo.auth0.com
  login: false

media_folder: "content/menu"
public_folder: "/content/menu"

site_url: https://lonjaprueba.netlify.app

auth:
  # Configuración para usar Auth0 como proveedor de autenticación OAuth2
  provider: oauth2
  base_url: https://dev-c2cpurjjmav12oqo.auth0.com
  client_id: D1nJbnBd4XLvO2kgzIwndAOPrLfbNx0X
  auth_endpoint: /authorize
  token_endpoint: /oauth/token
  userinfo_endpoint: /userinfo
  logout_endpoint: /v2/logout
  response_type: token
  grant_type: authorization_code
  scope: openid profile email
  redirect_uri: https://lonjaprueba.netlify.app/admin/
  logout_redirect_uri: https://lonjaprueba.netlify.app/

collections:
  - name: "menu"
    label: "Menú del Restaurante"
    folder: "content/menu"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Nombre del Plato"
        name: "title"
        widget: "string"
      - label: "Descripción"
        name: "description"
        widget: "text"
      - label: "Precio"
        name: "price"
        widget: "number"
      - label: "Categoría"
        name: "category"
        widget: "select"
        options:
          - "Entradas"
          - "Arroces y Pastas"
          - "Carnes"
          - "Pescado del Día"
          - "Mariscos"
          - "Postres"
          - "Bebidas"
          - "Vinos Tintos"
          - "Vinos Blancos"
      - label: "Imagen"
        name: "image"
        widget: "image"
        required: false
